<?php

namespace App\Filament\Resources\Categories\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class CategoryForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->required()
                    ->maxLength(255)
                    ->live(onBlur: true),

                // Auto-generated by Category::getSlugOptions() (Spatie
                // HasSlug) on save - shown read-only rather than editable,
                // so there's no risk of it drifting from `name`.
                TextInput::make('slug')
                    ->disabled()
                    ->dehydrated(false)
                    ->helperText('Generated automatically from the name.'),
            ]);
    }
}
