<?php

namespace App\Filament\Resources\Menus\Schemas;

use App\Models\Menu;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class MenuForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('title')
                    ->required()
                    ->maxLength(255)
                    ->live(onBlur: true),

                // Auto-generated by Menu::getSlugOptions() (Spatie HasSlug)
                // - read-only so it can never drift from title.
                TextInput::make('slug')
                    ->disabled()
                    ->dehydrated(false)
                    ->helperText('Generated automatically from the title.'),

                Select::make('parent_id')
                    ->label('Parent menu item')
                    ->relationship(
                        name: 'parent',
                        titleAttribute: 'title',
                        modifyQueryUsing: fn ($query) => $query->orderBy('title'),
                    )
                    ->getOptionLabelFromRecordUsing(fn (Menu $record) => $record->breadcrumb_path)
                    ->searchable()
                    ->preload()
                    ->helperText('Max nesting depth is 3 levels - Menu::guardAgainstExceedingMaxDepth() rejects the save if this would go deeper.'),

                Select::make('page_id')
                    ->label('Links to page')
                    ->relationship('page', 'title')
                    ->searchable()
                    ->preload()
                    ->helperText('A level-1 item with children is never clickable itself - it only toggles its dropdown, even if a page is set here.'),

                Toggle::make('is_active')
                    ->default(true),

                // sort_order is intentionally not a form field here - it's
                // controlled by the drag handle on the table, matching the
                // FAQ relation manager pattern.
            ]);
    }
}
