<?php

namespace App\Filament\Resources\Pages\Schemas;

use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\File;

class PageForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('title')
                    ->required()
                    ->maxLength(255)
                    ->live(onBlur: true),

                // Auto-generated by Page::getSlugOptions() (Spatie HasSlug)
                // on save - read-only so it can never drift from `title`.
                TextInput::make('slug')
                    ->disabled()
                    ->dehydrated(false)
                    ->helperText('Generated automatically from the title.'),

                // A dropdown of *actual* files on disk, not free text -
                // PageController::show() still re-checks File::exists()
                // before ever calling view(), but this closes off the easy
                // typo path at the source.
                Select::make('blade_file')
                    ->label('Blade template')
                    ->options(fn () => self::discoverBladeFiles())
                    ->searchable()
                    ->required()
                    ->helperText('Only existing files under resources/views/pages are listed.'),

                TextInput::make('meta_title')
                    ->maxLength(255),

                Textarea::make('meta_description')
                    ->maxLength(500)
                    ->columnSpanFull(),

                FileUpload::make('og_image')
                    ->image()
                    ->directory('pages')
                    ->maxSize(2048), // 2MB

                Toggle::make('is_indexable')
                    ->default(true)
                    ->helperText('Off emits <meta name="robots" content="noindex"> on this page.'),
            ]);
    }

    /**
     * @return array<string, string>
     */
    protected static function discoverBladeFiles(): array
    {
        $directory = resource_path('views/pages');

        if (! File::isDirectory($directory)) {
            return [];
        }

        return collect(File::allFiles($directory))
            ->filter(fn ($file) => str_ends_with($file->getFilename(), '.blade.php'))
            ->mapWithKeys(function ($file) {
                $relative = str($file->getRelativePathname())
                    ->replace('.blade.php', '')
                    ->replace('\\', '.')
                    ->replace('/', '.')
                    ->toString();

                return ['pages.'.$relative => 'pages.'.$relative];
            })
            ->toArray();
    }
}
