<?php

namespace App\Filament\Resources\Blogs\Schemas;

use App\Enums\BlogStatus;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\Auth;

class BlogForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Content')
                    ->columns(2)
                    ->components([
                        TextInput::make('title')
                            ->required()
                            ->maxLength(255)
                            ->live(onBlur: true)
                            ->columnSpanFull(),

                        // Auto-generated by Blog::getSlugOptions() (Spatie
                        // HasSlug) - read-only so it can never drift from title.
                        TextInput::make('slug')
                            ->disabled()
                            ->dehydrated(false)
                            ->helperText('Generated automatically from the title.')
                            ->columnSpanFull(),

                        Textarea::make('excerpt')
                            ->maxLength(500)
                            ->columnSpanFull(),

                        // Sanitized server-side in Blog::booted() (saving
                        // hook) regardless of what the toolbar allows here -
                        // never trust this as the safety boundary on its own.
                        RichEditor::make('body')
                            ->required()
                            ->columnSpanFull(),

                        FileUpload::make('featured_image')
                            ->image()
                            ->directory('blogs')
                            ->maxSize(2048), // 2MB
                    ]),

                Section::make('Publishing')
                    ->columns(2)
                    ->components([
                        Select::make('status')
                            ->options(BlogStatus::class)
                            ->default(BlogStatus::Draft)
                            ->required()
                            ->live(),

                        // Auto-set exactly once on first publish via
                        // Blog::booted() - shown read-only rather than
                        // editable, so there's no risk of backdating drift.
                        DateTimePicker::make('published_at')
                            ->disabled()
                            ->dehydrated(false)
                            ->visible(fn ($get) => $get('status') === BlogStatus::Published->value)
                            ->helperText('Set automatically the first time this post is published.'),

                        Select::make('user_id')
                            ->label('Author')
                            ->relationship('user', 'name')
                            ->default(fn () => Auth::id())
                            ->searchable()
                            ->preload(),

                        Select::make('category_id')
                            ->label('Category')
                            ->relationship('category', 'name')
                            ->searchable()
                            ->preload(),
                    ]),

                Section::make('SEO')
                    ->columns(2)
                    ->collapsible()
                    ->components([
                        TextInput::make('meta_title')
                            ->maxLength(255),

                        Textarea::make('meta_description')
                            ->maxLength(500),

                        FileUpload::make('og_image')
                            ->image()
                            ->directory('blogs')
                            ->maxSize(2048)
                            ->columnSpanFull(),
                    ]),
            ]);
    }
}
